### ISSUE TITLE
Extension Wants to Add ConfigureAwait to ConfiguredCancelableAsyncEnumerable Infinitely

### ISSUE THREAD

**Issue by CenturySparkle** [renestein/ConfigureAwaitEnforcer#6] opened 2021-10-12 18:32 UTC
When using async foreach, the returned type of source list is IAsyncEnumerable<T>.  After adding ConfigureAwait, the returned type is ConfiguredCancelableAsyncEnumerable<T>.  This extension wants to infinitely add ConfigureAwait to ConfiguredCancelableAsyncEnumerable<T> so that you wind up with code that looks like this:

await foreach(dynamic row in result.Rows.ConfigureAwait(false).ConfigureAwait(false).ConfigureAwait(false)) keys.Add(JObject.FromObject(row));

The error is never removed from the Error List window no matter how many times you add ConfigureAwait.

It's also a bit concerning that this is valid compilable code as well.

**Comment by renestein** [comment] 2021-10-13 12:49
Hi @CenturySparkle ,
and thanks for the report.
I am afraid that described problem is not caused by my extension.
I have tried to reproduce your issue (VS 2022 Preview). 
See the image.
Maybe you are using another extension? I think that VS 2022 has a 'Use ConfigureAwait(false) call' command (and you can see it in the image above) and I am pretty sure that this command causes a yellow 'exception occurred' message in the preview version of the Visual Studio.
![AwaitForEach](https://user-images.githubusercontent.com/386151/137135666-932f1b2e-a594-4ab0-bebc-4c8d50e852bf.gif)

**Comment by CenturySparkle** [comment] 2021-10-15 05:31
This may actually be a bug .Net Core 6.  I wouldn't think that ConfigureAwait would be a valid extension method of ConfiguredCancelableAsyncEnumerable.

**Comment by renestein** [comment] 2021-11-05 12:14
Closing, feel free to reopen.

**Closed as completed** 2021-11-05 12:14 UTC
Labels: invalid
